"""样例契约：一个「计算/查询服务」的声明式契约用例。

覆盖维度：正常调用、边界值、非法参数、缺失字段、异常类型、
超时、重复调用（幂等）、部分失败、副作用。
"""

CASES = [
    {
        "id": "add_basic",
        "category": "正常",
        "severity": "critical",
        "description": "加法基本功能",
        "op": "add",
        "input": {"a": 1, "b": 2},
        "expect": {"result": 3},
    },
    {
        "id": "transfer_audit",
        "category": "副作用",
        "severity": "minor",
        "description": "转账必须记录 audit 副作用",
        "op": "transfer",
        "input": {"amount": 5},
        "expect": {"result": 5},
        "side_effects": ["audit"],
    },
    {
        "id": "add_big_int",
        "category": "边界",
        "severity": "minor",
        "description": "大整数加法不得丢失精度",
        "op": "add",
        "input": {"a": 10 ** 30, "b": 1},
        "expect": {"result": 10 ** 30 + 1},
    },
    {
        "id": "add_invalid_type",
        "category": "非法参数",
        "severity": "critical",
        "description": "非数字参数必须抛 TypeError，不得静默转换",
        "op": "add",
        "input": {"a": "1", "b": 2},
        "expect": {"error": "TypeError"},
    },
    {
        "id": "add_missing_field",
        "category": "缺失字段",
        "severity": "major",
        "description": "缺少字段 b 必须抛 KeyError",
        "op": "add",
        "input": {"a": 1},
        "expect": {"error": "KeyError"},
    },
    {
        "id": "div_basic",
        "category": "正常",
        "severity": "major",
        "description": "除法基本功能",
        "op": "div",
        "input": {"a": 7, "b": 2},
        "expect": {"result": 3.5},
    },
    {
        "id": "div_by_zero",
        "category": "异常",
        "severity": "critical",
        "description": "除零必须抛 ZeroDivisionError",
        "op": "div",
        "input": {"a": 1, "b": 0},
        "expect": {"error": "ZeroDivisionError"},
    },
    {
        "id": "compute_timeout",
        "category": "超时",
        "severity": "major",
        "description": "compute 必须在 200ms 内返回",
        "op": "compute",
        "input": {"n": 10},
        "timeout_ms": 200,
        "expect": {"result": 55},
    },
    {
        "id": "balance_repeat",
        "category": "重复调用",
        "severity": "major",
        "description": "balance 为幂等查询，重复调用结果必须一致",
        "op": "balance",
        "input": {},
        "repeat": 3,
        "expect": {"result": 100},
    },
    {
        "id": "batch_partial",
        "category": "部分失败",
        "severity": "critical",
        "description": "批量除法部分失败时返回部分结果与错误列表，不得整体失败",
        "op": "batch_div",
        "input": {"pairs": [[1, 1], [1, 0], [4, 2]]},
        "expect": {"result": {
            "results": [1.0, 2.0],
            "errors": [{"index": 1, "error": "ZeroDivisionError"}],
        }},
    },
]
